### PR TITLE
Kratos API token retrievable cross-domain

### PR DESCRIPTION
**Pull request by valentinyanakiev**
Multiple issues fixed / to focus on during the review:
- Kratos API Endpoint Factory is replaced with a config. Easier to debug + trace issues that way.
- Changed the Action URI logic for API logins. The orthodox Kratos flow is not cross-domain, and even in dev scenarios it builds the action URI in one domain, the one defined in kratos.yml, completely ignoring the baseURL configuration
- Changed the Kratos API Base URL logic - it was making a call out to the server api to retrieve the configuration, even when one was provided
- Added additional logging. To be discussed how / whether to keep it.

### CODE REVIEW

**Review by techsmyth — APPROVED** [review]
Changes make sense. I modified the logic in one method to make clear when getting server config + that that is logged. 

Note: have not been able to run this to test the cross domain setup. That needs a discussion / verification.

**Comment by valentinyanakiev** [comment]
> Changes make sense. I modified the logic in one method to make clear when getting server config + that that is logged.
> 
> Note: have not been able to run this to test the cross domain setup. That needs a discussion / verification.

I can provide a config to test it on server repo from a branch. To test it properly, I need to open the PR on notifications repo to fix the issues there as well, we release it and use it in the server.

**Comment by valentinyanakiev** [comment]
I stumbled upon a small issue running the code - combining the URLs. I will push a fix for it. Also, something we need to be on the lookout for is the fact that we are running Kratos with --dev flag in our docker compose setup and in production we don't. There are differences and we need to be careful with URL resolution and put emphasis on its validation.

**Comment by valentinyanakiev** [comment]
Added the URL fix, should be good to go...

**Pull request merged**
